import { BaseCart } from '../chichicarts/BaseCart';
import { ChiChiAPU } from './ChiChiAudio';
import { RunningStatuses } from './ChiChiTypes';
import { ChiChiControlPad } from './ChiChiControl';
import { IChiChiPPU } from "./ChiChiPPU";
import { WavSharer } from './Audio/CommonAudio';
import { ChiChiCPPU } from './ChiChiCPU';
export declare class ChiChiMachine {
    private frameJustEnded;
    private frameOn;
    private totalCPUClocks;
    constructor(cpu?: ChiChiCPPU);
    Drawscreen(): void;
    RunState: RunningStatuses;
    ppu: IChiChiPPU;
    Cpu: ChiChiCPPU;
    readonly Cart: BaseCart;
    SoundBopper: ChiChiAPU;
    WaveForms: WavSharer;
    private _enableSound;
    EnableSound: boolean;
    FrameCount: number;
    IsRunning: boolean;
    readonly PadOne: ChiChiControlPad;
    readonly PadTwo: ChiChiControlPad;
    Reset(): void;
    PowerOn(): void;
    PowerOff(): void;
    Step(): void;
    evenFrame: boolean;
    RunFrame(): void;
    EjectCart(): void;
    LoadNSF(rom: any): void;
    frameFinished(): void;
    dispose(): void;
}
