import { BaseCart } from "./BaseCart";
export declare class KonamiVRC2Cart extends BaseCart {
    microwireLatch: number;
    irqCounter: number;
    irqMode: boolean;
    irqEnableAfterAck: boolean;
    irqEnable: boolean;
    chrbank0: number;
    chrbank0_1: number;
    chrbank1: number;
    chrbank1_1: number;
    chrbankc1_1: number;
    chrbankc1: number;
    chrbankc0_1: number;
    chrbankc0: number;
    chrbankd1_1: number;
    chrbankd1: number;
    chrbankd0_1: number;
    chrbankd0: number;
    chrbanke1_1: number;
    chrbanke1: number;
    chrbanke0_1: number;
    chrbanke0: number;
    latches: number[];
    regNums: number[];
    irqLatch: number;
    advanceClock(clock: number): void;
    ackIrq(): void;
    irqControl: number;
    InitializeCart(): void;
    GetByte(clock: number, address: number): number;
    SetByte(clock: number, address: number, data: number): void;
}
export declare class KonamiVRC022Cart extends BaseCart {
    microwireLatch: number;
    irqCounter: number;
    irqMode: boolean;
    irqEnableAfterAck: boolean;
    irqEnable: boolean;
    chrbank0: number;
    chrbank0_1: number;
    chrbank1: number;
    chrbank1_1: number;
    chrbankc1_1: number;
    chrbankc1: number;
    chrbankc0_1: number;
    chrbankc0: number;
    chrbankd1_1: number;
    chrbankd1: number;
    chrbankd0_1: number;
    chrbankd0: number;
    chrbanke1_1: number;
    chrbanke1: number;
    chrbanke0_1: number;
    chrbanke0: number;
    latches: number[];
    regNums: number[];
    irqLatch: number;
    advanceClock(clock: number): void;
    ackIrq(): void;
    irqControl: number;
    InitializeCart(): void;
    SetByte(clock: number, address: number, data: number): void;
}
export declare class Konami021Cart extends BaseCart {
    swapMode: boolean;
    microwireLatch: number;
    irqCounter: number;
    irqMode: boolean;
    irqEnableAfterAck: boolean;
    irqEnable: boolean;
    chrbank0: number;
    chrbank0_1: number;
    chrbank1: number;
    chrbank1_1: number;
    chrbankc1_1: number;
    chrbankc1: number;
    chrbankc0_1: number;
    chrbankc0: number;
    chrbankd1_1: number;
    chrbankd1: number;
    chrbankd0_1: number;
    chrbankd0: number;
    chrbanke1_1: number;
    chrbanke1: number;
    chrbanke0_1: number;
    chrbanke0: number;
    latches: number[];
    regNums: number[];
    irqLatch: number;
    advanceClock(clock: number): void;
    ackIrq(): void;
    irqControl: number;
    InitializeCart(): void;
    SetByte(clock: number, address: number, data: number): void;
}
export declare class Konami025Cart extends BaseCart {
    swapMode: boolean;
    microwireLatch: number;
    irqCounter: number;
    irqMode: boolean;
    irqEnableAfterAck: boolean;
    irqEnable: boolean;
    chrbank0: number;
    chrbank0_1: number;
    chrbank1: number;
    chrbank1_1: number;
    chrbankc1_1: number;
    chrbankc1: number;
    chrbankc0_1: number;
    chrbankc0: number;
    chrbankd1_1: number;
    chrbankd1: number;
    chrbankd0_1: number;
    chrbankd0: number;
    chrbanke1_1: number;
    chrbanke1: number;
    chrbanke0_1: number;
    chrbanke0: number;
    latches: number[];
    regNums: number[];
    irqLatch: number;
    advanceClock(clock: number): void;
    ackIrq(): void;
    irqControl: number;
    InitializeCart(): void;
    SetByte(clock: number, address: number, data: number): void;
}
